// packages/react/src/plugins/slot.tsx
import {
  createSlotRegistry,
  SlotRegistry,
  type CliRenderer,
  type Plugin,
  type PluginContext,
  type PluginErrorEvent,
  type ResolvedSlotRenderer,
  type SlotMode,
  type SlotRegistryOptions,
} from "@lexwdex-org/core"
import React, { Fragment, useEffect, useMemo, useRef, useState } from "react"
import type { ReactNode } from "react"

export type { SlotMode }
type SlotMap = Record<string, object>

export type ReactPlugin<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = Plugin<
  ReactNode,
  TSlots,
  TContext
>

export type ReactSlotProps<
  TSlots extends SlotMap,
  K extends keyof TSlots,
  TContext extends PluginContext = PluginContext,
> = {
  registry: SlotRegistry<ReactNode, TSlots, TContext>
  name: K
  mode?: SlotMode
  children?: ReactNode
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => ReactNode
} & TSlots[K]

export type ReactBoundSlotProps<TSlots extends SlotMap, K extends keyof TSlots> = {
  name: K
  mode?: SlotMode
  children?: ReactNode
} & TSlots[K]

export type ReactRegistrySlotComponent<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = <
  K extends keyof TSlots,
>(
  props: ReactSlotProps<TSlots, K, TContext>,
) => ReactNode

export type ReactSlotComponent<TSlots extends SlotMap> = <K extends keyof TSlots>(
  props: ReactBoundSlotProps<TSlots, K>,
) => ReactNode

export interface ReactSlotOptions {
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => ReactNode
}

export function createReactSlotRegistry<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  renderer: CliRenderer,
  context: TContext,
  options: SlotRegistryOptions = {},
): SlotRegistry<ReactNode, TSlots, TContext> {
  // React slots intentionally use one registry key per renderer instance.
  // Use createSlotRegistry from @lexwdex-org/core with a custom key for independent registries.
  return createSlotRegistry<ReactNode, TSlots, TContext>(renderer, "react:slot-registry", context, options)
}

type PluginErrorBoundaryProps = {
  registry: SlotRegistry<ReactNode, any, any>
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => ReactNode
  pluginId: string
  slotName: string
  resetToken: number
  fallbackOnFailure?: ReactNode
  children: ReactNode
}

type PluginErrorBoundaryState = {
  failure: PluginErrorEvent | null
}

function renderPluginFailurePlaceholder(
  registry: SlotRegistry<ReactNode, any, any>,
  pluginFailurePlaceholder: ((failure: PluginErrorEvent) => ReactNode) | undefined,
  failure: PluginErrorEvent,
  pluginId: string,
  slot: string,
): ReactNode {
  if (!pluginFailurePlaceholder) {
    return null
  }

  try {
    return pluginFailurePlaceholder(failure)
  } catch (error) {
    registry.reportPluginError({
      pluginId,
      slot,
      phase: "error_placeholder",
      source: "react",
      error,
    })

    return null
  }
}

class PluginErrorBoundary extends React.Component<PluginErrorBoundaryProps, PluginErrorBoundaryState> {
  constructor(props: PluginErrorBoundaryProps) {
    super(props)
    this.state = { failure: null }
  }

  override componentDidCatch(error: Error): void {
    const failure = this.props.registry.reportPluginError({
      pluginId: this.props.pluginId,
      slot: this.props.slotName,
      phase: "render",
      source: "react",
      error,
    })

    this.setState({ failure })
  }

  override componentDidUpdate(previousProps: PluginErrorBoundaryProps): void {
    if (previousProps.resetToken !== this.props.resetToken && this.state.failure) {
      this.setState({ failure: null })
    }
  }

  override render(): ReactNode {
    if (this.state.failure) {
      const placeholder = renderPluginFailurePlaceholder(
        this.props.registry,
        this.props.pluginFailurePlaceholder,
        this.state.failure,
        this.props.pluginId,
        this.props.slotName,
      )

      if (placeholder === null || placeholder === undefined || placeholder === false) {
        return this.props.fallbackOnFailure ?? null
      }

      return placeholder
    }

    return this.props.children
  }
}

function getSlotProps<TSlots extends SlotMap, K extends keyof TSlots, TContext extends PluginContext = PluginContext>(
  props: ReactSlotProps<TSlots, K, TContext>,
): TSlots[K] {
  const {
    children: _children,
    mode: _mode,
    name: _name,
    registry: _registry,
    pluginFailurePlaceholder: _pluginFailurePlaceholder,
    ...slotProps
  } = props
  return slotProps as TSlots[K]
}

export function createSlot<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  registry: SlotRegistry<ReactNode, TSlots, TContext>,
  options: ReactSlotOptions = {},
): ReactSlotComponent<TSlots> {
  return function BoundSlot<K extends keyof TSlots>(props: ReactBoundSlotProps<TSlots, K>): ReactNode {
    return (
      <Slot<TSlots, TContext, K>
        {...(props as ReactBoundSlotProps<TSlots, K>)}
        registry={registry}
        pluginFailurePlaceholder={options.pluginFailurePlaceholder}
      />
    )
  }
}

export function Slot<
  TSlots extends SlotMap,
  TContext extends PluginContext = PluginContext,
  K extends keyof TSlots = keyof TSlots,
>(props: ReactSlotProps<TSlots, K, TContext>): ReactNode {
  const [version, setVersion] = useState(0)
  const registry = props.registry
  const slotName = String(props.name)
  const renderFailuresByPluginRef = useRef<Map<string, PluginErrorEvent>>(new Map())
  const pendingRenderReportsRef = useRef<Map<string, { pluginId: string; slot: string; error: Error }>>(new Map())

  useEffect(() => {
    return registry.subscribe(() => {
      setVersion((current) => current + 1)
    })
  }, [registry])

  useEffect(() => {
    if (pendingRenderReportsRef.current.size === 0) {
      return
    }

    const pendingReports = [...pendingRenderReportsRef.current.values()]
    pendingRenderReportsRef.current.clear()

    for (const report of pendingReports) {
      const failure = registry.reportPluginError({
        pluginId: report.pluginId,
        slot: report.slot,
        phase: "render",
        source: "react",
        error: report.error,
      })

      renderFailuresByPluginRef.current.set(`${report.slot}:${report.pluginId}:render`, failure)
    }
  })

  const entries = useMemo<Array<ResolvedSlotRenderer<ReactNode, TSlots[K], TContext>>>(
    () => registry.resolveEntries(props.name),
    [registry, props.name, version],
  )
  const slotProps = getSlotProps(props)

  const renderEntry = (
    entry: ResolvedSlotRenderer<ReactNode, TSlots[K], TContext>,
    fallbackOnFailure?: ReactNode,
  ): ReactNode => {
    const key = `${slotName}:${entry.id}`
    const failureKey = `${slotName}:${entry.id}:render`

    try {
      const rendered = entry.renderer(registry.context, slotProps)
      renderFailuresByPluginRef.current.delete(failureKey)
      pendingRenderReportsRef.current.delete(failureKey)
      return (
        <PluginErrorBoundary
          key={key}
          registry={registry}
          pluginFailurePlaceholder={props.pluginFailurePlaceholder}
          pluginId={entry.id}
          slotName={slotName}
          resetToken={version}
          fallbackOnFailure={fallbackOnFailure}
        >
          {rendered}
        </PluginErrorBoundary>
      )
    } catch (error) {
      const normalizedError =
        error instanceof Error ? error : typeof error === "string" ? new Error(error) : new Error(String(error))
      const lastFailure = renderFailuresByPluginRef.current.get(failureKey)
      const isSameFailure = lastFailure && lastFailure.error.message === normalizedError.message

      if (!isSameFailure) {
        const queued = pendingRenderReportsRef.current.get(failureKey)
        if (!queued || queued.error.message !== normalizedError.message) {
          pendingRenderReportsRef.current.set(failureKey, {
            pluginId: entry.id,
            slot: slotName,
            error: normalizedError,
          })
        }
      }

      const failure: PluginErrorEvent =
        isSameFailure && lastFailure
          ? lastFailure
          : {
              pluginId: entry.id,
              slot: slotName,
              phase: "render",
              source: "react",
              error: normalizedError,
              timestamp: Date.now(),
            }

      renderFailuresByPluginRef.current.set(failureKey, failure)

      const placeholder = renderPluginFailurePlaceholder(
        registry,
        props.pluginFailurePlaceholder,
        failure,
        entry.id,
        slotName,
      )
      if (placeholder === null || placeholder === undefined || placeholder === false) {
        return fallbackOnFailure ?? null
      }

      return <Fragment key={key}>{placeholder}</Fragment>
    }
  }

  if (entries.length === 0) {
    return <>{props.children}</>
  }

  if (props.mode === "single_winner") {
    const winner = entries[0]
    if (!winner) {
      return <>{props.children}</>
    }

    const rendered = renderEntry(winner, props.children)
    if (rendered === null || rendered === undefined || rendered === false) {
      return <>{props.children}</>
    }

    return <>{rendered}</>
  }

  if (props.mode === "replace") {
    if (entries.length === 1) {
      const rendered = renderEntry(entries[0], props.children)
      if (rendered === null || rendered === undefined || rendered === false) {
        return <>{props.children}</>
      }

      return <>{rendered}</>
    }

    const renderedEntries = entries.map((entry) => renderEntry(entry))
    const hasPluginOutput = renderedEntries.some((node) => node !== null && node !== undefined && node !== false)

    if (!hasPluginOutput) {
      return <>{props.children}</>
    }

    return <>{renderedEntries}</>
  }

  return (
    <>
      {props.children}
      {entries.map((entry) => renderEntry(entry))}
    </>
  )
}

// packages/solid/src/plugins/slot.tsx
import {
  createSlotRegistry,
  SlotRegistry,
  type CliRenderer,
  type Plugin,
  type PluginContext,
  type PluginErrorEvent,
  type ResolvedSlotRenderer,
  type SlotMode,
  type SlotRegistryOptions,
} from "@lexwdex-org/core"
import { children, createMemo, createSignal, ErrorBoundary, For, onCleanup, splitProps, type JSX } from "solid-js"

export type { SlotMode }
type SlotMap = Record<string, object>
const EMPTY_ENTRY_IDS: string[] = []

export type SolidPlugin<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = Plugin<
  JSX.Element,
  TSlots,
  TContext
>

export type SolidSlotProps<
  TSlots extends SlotMap,
  K extends keyof TSlots,
  TContext extends PluginContext = PluginContext,
> = {
  registry: SlotRegistry<JSX.Element, TSlots, TContext>
  name: K
  mode?: SlotMode
  children?: JSX.Element
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => JSX.Element
} & TSlots[K]

export type SolidBoundSlotProps<TSlots extends SlotMap, K extends keyof TSlots> = {
  name: K
  mode?: SlotMode
  children?: JSX.Element
} & TSlots[K]

export type SolidRegistrySlotComponent<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = <
  K extends keyof TSlots,
>(
  props: SolidSlotProps<TSlots, K, TContext>,
) => JSX.Element

export type SolidSlotComponent<TSlots extends SlotMap> = <K extends keyof TSlots>(
  props: SolidBoundSlotProps<TSlots, K>,
) => JSX.Element

export interface SolidSlotOptions {
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => JSX.Element
}

export function createSolidSlotRegistry<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  renderer: CliRenderer,
  context: TContext,
  options: SlotRegistryOptions = {},
): SlotRegistry<JSX.Element, TSlots, TContext> {
  // Solid slots intentionally use one registry key per renderer instance.
  // Use createSlotRegistry from @lexwdex-org/core with a custom key for independent registries.
  return createSlotRegistry<JSX.Element, TSlots, TContext>(renderer, "solid:slot-registry", context, options)
}

export function createSlot<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  registry: SlotRegistry<JSX.Element, TSlots, TContext>,
  options: SolidSlotOptions = {},
): SolidSlotComponent<TSlots> {
  return function BoundSlot<K extends keyof TSlots>(props: SolidBoundSlotProps<TSlots, K>): JSX.Element {
    return (
      <Slot<TSlots, TContext, K>
        {...(props as SolidBoundSlotProps<TSlots, K>)}
        registry={registry}
        pluginFailurePlaceholder={options.pluginFailurePlaceholder}
      />
    )
  }
}

export function Slot<
  TSlots extends SlotMap,
  TContext extends PluginContext = PluginContext,
  K extends keyof TSlots = keyof TSlots,
>(props: SolidSlotProps<TSlots, K, TContext>): JSX.Element {
  const [local, slotProps] = splitProps(props as SolidSlotProps<TSlots, K, TContext>, [
    "registry",
    "name",
    "mode",
    "children",
    "pluginFailurePlaceholder",
  ])
  const registry = () => local.registry
  const pluginFailurePlaceholder = () => local.pluginFailurePlaceholder
  const [version, setVersion] = createSignal(0)
  let queued = false
  let disposed = false

  const unsubscribe = registry().subscribe(() => {
    if (queued) return
    queued = true
    setVersion((current) => current + 1)
    queueMicrotask(() => {
      queued = false
      if (disposed) return
    })
  })
  onCleanup(() => {
    disposed = true
    unsubscribe()
  })

  const entries = createMemo<Array<ResolvedSlotRenderer<JSX.Element, TSlots[K], TContext>>>((previousEntries = []) => {
    version()
    const resolvedEntries = registry().resolveEntries(local.name as K) as Array<
      ResolvedSlotRenderer<JSX.Element, TSlots[K], TContext>
    >

    if (resolvedEntries.length === 0) {
      if (previousEntries.length === 0) return previousEntries
      return []
    }

    const previousById = new Map(previousEntries.map((entry) => [entry.id, entry]))
    const nextEntries = resolvedEntries.map((entry) => {
      const previousEntry = previousById.get(entry.id)
      if (previousEntry && previousEntry.renderer === entry.renderer) {
        return previousEntry
      }

      return entry
    })

    const unchanged =
      nextEntries.length === previousEntries.length &&
      nextEntries.every((entry, index) => entry === previousEntries[index])
    if (unchanged) return previousEntries

    return nextEntries
  })

  const entryIds = createMemo(() => entries().map((entry) => entry.id))
  const entriesById = createMemo(() => new Map(entries().map((entry) => [entry.id, entry])))

  const slotName = () => String(local.name)

  const renderFallback = (): JSX.Element => {
    const value = children(() => local.children)()
    return (value ?? null) as JSX.Element
  }

  const resolveFallback = (fallbackValue?: (() => JSX.Element) | undefined): JSX.Element => fallbackValue?.() ?? null

  const renderPluginFailurePlaceholder = (
    failure: PluginErrorEvent,
    fallbackValue?: (() => JSX.Element) | undefined,
  ): JSX.Element => {
    if (!pluginFailurePlaceholder()) {
      return resolveFallback(fallbackValue)
    }

    try {
      return pluginFailurePlaceholder()!(failure)
    } catch (error) {
      registry().reportPluginError({
        pluginId: failure.pluginId,
        slot: failure.slot ?? slotName(),
        phase: "error_placeholder",
        source: "solid",
        error,
      })

      return resolveFallback(fallbackValue)
    }
  }

  const renderEntry = (
    entry: ResolvedSlotRenderer<JSX.Element, TSlots[K], TContext>,
    fallbackOnError?: () => JSX.Element,
  ): JSX.Element => {
    let initialRender: JSX.Element

    try {
      initialRender = entry.renderer(registry().context, slotProps as TSlots[K])
    } catch (error) {
      const failure = registry().reportPluginError({
        pluginId: entry.id,
        slot: slotName(),
        phase: "render",
        source: "solid",
        error,
      })

      return renderPluginFailurePlaceholder(failure, fallbackOnError)
    }

    const resolvedInitialRender = children(() => initialRender)
    const hasInitialOutput = resolvedInitialRender
      .toArray()
      .some((node) => node !== null && node !== undefined && node !== false)

    if (!hasInitialOutput) {
      return resolveFallback(fallbackOnError)
    }

    return (
      <ErrorBoundary
        fallback={(error: unknown) => {
          const failure = registry().reportPluginError({
            pluginId: entry.id,
            slot: slotName(),
            phase: "render",
            source: "solid",
            error,
          })

          return renderPluginFailurePlaceholder(failure, fallbackOnError)
        }}
      >
        {resolvedInitialRender()}
      </ErrorBoundary>
    )
  }

  const AppendEntry = (appendProps: { entryId: string }): JSX.Element => {
    const entry = createMemo(() => entriesById().get(appendProps.entryId))

    return (
      <>
        {(() => {
          const resolvedEntry = entry()
          if (!resolvedEntry) {
            return null
          }

          return renderEntry(resolvedEntry)
        })()}
      </>
    )
  }

  const appendEntryIds = createMemo(() => {
    const mode = local.mode ?? "append"
    if (mode !== "append") {
      return EMPTY_ENTRY_IDS
    }

    return entryIds()
  })

  const appendView = (
    <>
      {renderFallback}
      <For each={appendEntryIds()}>{(entryId) => <AppendEntry entryId={entryId} />}</For>
    </>
  )

  return (
    <>
      {(() => {
        const resolvedEntries = entries()
        const mode = local.mode ?? "append"

        if (resolvedEntries.length === 0) {
          return renderFallback()
        }

        if (mode === "single_winner") {
          const winner = resolvedEntries[0]
          if (!winner) {
            return renderFallback()
          }

          return renderEntry(winner, renderFallback)
        }

        if (mode === "replace") {
          const renderedEntries = resolvedEntries.map((entry) => renderEntry(entry))
          const hasPluginOutput = renderedEntries.some(
            (entry) => entry !== null && entry !== undefined && entry !== false,
          )

          if (!hasPluginOutput) {
            return renderFallback()
          }

          return <>{renderedEntries}</>
        }

        return appendView
      })()}
    </>
  )
}
