// packages/react/dist-test/nodejs-typescript/index.tsx
import assert from "node:assert/strict"
import { describe, it } from "node:test"
import { createCliRenderer } from "@opentui/core"
import { createTestRenderer } from "@opentui/core/testing"
import { createRoot } from "@opentui/react"
import { testRender } from "@opentui/react/test-utils"
import { act, useState, useEffect, type ReactNode } from "react"

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("@opentui/react dist test (Node.js + TypeScript)", () => {
  it("imports react public entrypoints", async () => {
    const react = await import("@opentui/react")
    const testUtils = await import("@opentui/react/test-utils")

    assert.equal(typeof react.createRoot, "function")
    assert.equal(typeof react.useKeyboard, "function")
    assert.equal(typeof react.useRenderer, "function")
    assert.equal(typeof testUtils.testRender, "function")
  })

  it("renders simple text via testRender", async () => {
    const { renderer, renderOnce, captureCharFrame } = await testRender(<text>Hello from React dist test</text>, {
      width: 40,
      height: 4,
    })

    try {
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Hello from React dist test/)
    } finally {
      renderer.destroy()
    }
  })

  it("renders nested box layout", async () => {
    const { renderer, renderOnce, captureCharFrame } = await testRender(
      <box style={{ flexDirection: "column" }}>
        <text>Line A</text>
        <text>Line B</text>
      </box>,
      { width: 30, height: 6 },
    )

    try {
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Line A/)
      assert.match(frame, /Line B/)
    } finally {
      renderer.destroy()
    }
  })

  it("renders a stateful component", async () => {
    function Counter({ initial }: { initial: number }): ReactNode {
      const [count] = useState(initial)
      return <text>{`Count: ${count}`}</text>
    }

    const { renderer, renderOnce, captureCharFrame } = await testRender(<Counter initial={42} />, {
      width: 20,
      height: 4,
    })

    try {
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Count: 42/)
    } finally {
      renderer.destroy()
    }
  })

  it("renders a box with border", async () => {
    const { renderer, renderOnce, captureCharFrame } = await testRender(
      <box title="Greetings" style={{ border: true, width: 25, height: 5 }}>
        <text>Boxed content</text>
      </box>,
      { width: 30, height: 8 },
    )

    try {
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Greetings/)
      assert.match(frame, /Boxed content/)
    } finally {
      renderer.destroy()
    }
  })

  it("uses createRoot directly with createTestRenderer", async () => {
    const { renderer, renderOnce, captureCharFrame } = await createTestRenderer({
      width: 30,
      height: 4,
    })

    // @ts-expect-error - required for React act() to work in test environment
    globalThis.IS_REACT_ACT_ENVIRONMENT = true
    const root = createRoot(renderer)

    try {
      act(() => {
        root.render(<text>Direct root render</text>)
      })
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Direct root render/)
    } finally {
      act(() => {
        root.unmount()
      })
      renderer.destroy()
      // @ts-expect-error
      globalThis.IS_REACT_ACT_ENVIRONMENT = false
    }
  })
})

// ---------------------------------------------------------------------------
// Interactive app — runs when executed directly: node dist/index.js
// ---------------------------------------------------------------------------

function InteractiveApp(): ReactNode {
  const [counter, setCounter] = useState(0)
  const [dots, setDots] = useState("")

  useEffect(() => {
    const interval = setInterval(() => {
      setCounter((c) => c + 1)
      setDots((d) => (d.length >= 3 ? "" : d + "."))
    }, 500)
    return () => clearInterval(interval)
  }, [])

  return (
    <box style={{ flexDirection: "column", padding: 1 }}>
      <box title="React Dist Test" style={{ border: true, width: 40, height: 5 }}>
        <text>{`Counter: ${counter}${dots}`}</text>
      </box>
      <text style={{ fg: "#888888" }}>Press Ctrl+C to exit</text>
    </box>
  )
}

if (process.env.NODE_TEST_CONTEXT === undefined && import.meta.main) {
  const renderer = await createCliRenderer()
  createRoot(renderer).render(<InteractiveApp />)
}

// packages/solid/dist-test/nodejs-typescript/index.tsx
import assert from "node:assert/strict"
import { describe, it } from "node:test"
import { render, testRender, useRenderer } from "@opentui/solid"
import { onMount } from "solid-js"

const initialDraft = "Welcome to the Solid dist test."

export function SolidDistTextareaDemo() {
  const renderer = useRenderer()

  onMount(() => {
    renderer.setBackgroundColor("#111827")
  })

  return (
    <box style={{ padding: 1, flexDirection: "column" }}>
      <box
        title="Solid Dist Textarea Demo"
        border
        borderColor="#6BCF7F"
        titleAlignment="left"
        paddingLeft={1}
        paddingRight={1}
        style={{ height: 8 }}
      >
        <textarea
          ref={(renderable) => {
            queueMicrotask(() => {
              if (renderable && !renderable.isDestroyed) {
                renderable.focus()
                renderable.gotoBufferEnd()
              }
            })
          }}
          focused
          initialValue={initialDraft}
          wrapMode="word"
          showCursor
          cursorColor="#7DD3FC"
          textColor="#E5E7EB"
          placeholder="Type here..."
          style={{ flexGrow: 1 }}
        />
      </box>
      <text style={{ fg: "#A5D6FF" }}>Solid textarea ready</text>
      <text style={{ fg: "#94A3B8" }}>Type in the textarea. Press Ctrl+C to exit.</text>
    </box>
  )
}

describe("@opentui/solid dist test (Node.js + TypeScript)", () => {
  it("imports solid public entrypoints", async () => {
    const solid = await import("@opentui/solid")

    assert.equal(typeof solid.render, "function")
    assert.equal(typeof solid.testRender, "function")
    assert.equal(typeof solid.useKeyboard, "function")
    assert.equal(typeof solid.useRenderer, "function")
  })

  it("renders the textarea demo", async () => {
    const { renderer, renderOnce, captureCharFrame } = await testRender(SolidDistTextareaDemo, {
      width: 64,
      height: 14,
    })

    try {
      await renderOnce()
      const frame = captureCharFrame()
      assert.match(frame, /Solid Dist Textarea Demo/)
      assert.match(frame, /Welcome to the Solid dist test\./)
      assert.match(frame, /Solid textarea ready/)
      assert.match(frame, /Type in the textarea\. Press Ctrl\+C to exit\./)
    } finally {
      renderer.destroy()
    }
  })

  it("updates textarea state from keyboard input", async () => {
    const { renderer, renderOnce, captureCharFrame, mockInput } = await testRender(SolidDistTextareaDemo, {
      width: 72,
      height: 14,
    })

    try {
      await renderOnce()

      await mockInput.typeText(" Running under Node")
      await renderOnce()

      let frame = captureCharFrame()
      assert.match(frame, /Running under Node/)
      assert.match(frame, /Solid textarea ready/)
    } finally {
      renderer.destroy()
    }
  })
})

if (process.env.NODE_TEST_CONTEXT === undefined && import.meta.main) {
  await render(SolidDistTextareaDemo, { exitOnCtrlC: true })
}
